Adding composition operator (>>>)
wayfair/prelude pull request #13
Opened 2019-03-20 19:45 UTC by dalkire

The compose operator ">>" provides an infix notation for function composition.
Composing a function that goes from A -> B with a function that goes from B -> C creates a new function that goes from A -> C.

Also added a tests.

2019-03-28 17:47 UTC, peter-tomaselli requested changes
Looks good! I do think that we need to carefully noodle around with the operator precedences and whatnot to make sure that everything plays well together.

2019-03-28 17:47 UTC, peter-tomaselli commented on Sources/Prelude/Operators.swift
> +    higherThan: LogicalConjunctionPrecedence
Does this make mixtures of `>>>` and `|>` ambiguous (they both have the same precedence)?

EDIT: I also think (could be wrong) that we want this to be `associativity: right`, as well.

2019-03-28 17:47 UTC, peter-tomaselli commented on Sources/Prelude/Prelude.swift
> +public func >>><A, B, C>(f: @escaping (A) -> B, g: @escaping (B) -> C) -> ((A) -> C) {
Sorry, annoying style comment. I think my preference here would be to spell the `f` argument `lhs`, and the `g` argument `rhs`, thus emphasizing the operatorness of this function. No worries if you disagree, but it’s what I’ve been trying to do so far.

Also, you should be able to spell the end of this signature without the last outer pair of parens!
```
((A) -> B, (B) -> C) -> (A) -> C { …
```

2019-04-01 18:24 UTC, dalkire commented on Sources/Prelude/Operators.swift
> +    higherThan: LogicalConjunctionPrecedence
You're right. Fixed. Added additional tests.

2019-04-01 18:24 UTC, dalkire commented on Sources/Prelude/Prelude.swift
> +public func >>><A, B, C>(f: @escaping (A) -> B, g: @escaping (B) -> C) -> ((A) -> C) {
Fixed

2019-04-01 20:43 UTC, peter-tomaselli approved these changes

2019-04-02 13:22 UTC, merged